---
title: "Actividad 1"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(flexdashboard)
library(palmerpenguins)
library(ggplot2)
library(dplyr)
```

Row
-----------------------------------------------------------------------

### Longitud de pico por especie y sexo

```{r}
tmp <- penguins %>%
  filter(!is.na(sex))

ggplot(tmp) +
  geom_histogram(aes(x = bill_length_mm, fill = sex), bins = 10) +
  facet_grid(species ~ sex) +
  theme_minimal()
```


Row
-----------------------------------------------------------------------

### Longitud de pico por especie y sexo

```{r}
ggplot(penguins) +
  geom_point(aes(x = bill_length_mm, y = bill_depth_mm, color = species)) +
  theme_minimal()
```

Row
-----------------------------------------------------------------------

### Longitud de pico por especie y sexo

```{r}
ggplot(tmp) +
  geom_violin(aes(x = sex, y = body_mass_g, fill = sex)) +
  theme_minimal()
```
